[tool.poetry]
name = "task1"
version = "0.1.0"
description = ""
authors = ["afro_0 <kirillov2136@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^7.4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
